services:

  node-web-app:
    build: .
    # image: node:18-alpine
    restart: always
    ports:
      - 40001:40001
    volumes:
      - ./src:/app/scr
    command: nodemon ./scr/server.js
    #command: node ./scr/server.js
